name: Check Python code formatting

on:
  push:
    paths:
      - 'intg-denonavr/**'
      - 'requirements.txt'
      - 'test-requirements.txt'
      - 'tests/**'
      - '.github/**/*.yml'
      - '.pylintrc'
      - 'pyproject.toml'
      - 'tox.ini'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

env:
  INTG_LIB_VER: 0.0.10

jobs:
  test:
    runs-on: ubuntu-22.04

    name: Check Python code formatting
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      # We need the integration library, this is temporary until we decide to publish it to pypi
      - name: Clone & install integrations library
        shell: bash
        run: |
          git clone https://martonborzak:${{ secrets.PAT }}@github.com/aitatoi/integration-python-library.git
          cd integration-python-library
          git checkout v${INTG_LIB_VER}
          pip install wheel
          python setup.py bdist_wheel
          ls -lah dist
          pip install -I dist/ucapi-${INTG_LIB_VER}-py3-none-any.whl

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Analyzing the code with pylint
        run: |
          python -m pylint intg-denonavr
      - name: Lint with flake8
        run: |
          python -m flake8 intg-denonavr --count --show-source --statistics
      - name: Check code formatting with isort
        run: |
          python -m isort intg-denonavr/. --check --verbose
      - name: Check code formatting with black
        run: |
          python -m black intg-denonavr --check --verbose --line-length 120
